# Please keep this as true in while using TCPShield!
only-allow-proxy-connections = true

# Turn off if you cannot change the machine clock and timestamp issues arise (not recommended)
timestamp-validation = true

# Turn on to diagnose connection issues
debug-mode = false